### ISSUE TITLE
Quite elaborated feature

### ISSUE THREAD

**Issue by Hannes-III** [salsita/chili#13]
As I was playing around with inStile, I checked different use-cases  where it would make sense to use it.
I used it in a placeholder. Unfortunately it did not work:

``` SCSS
%xxx{
    @include in(  "<.new"){color:red}
}

.x1{
    .x2{
        .x3{
            .current{
                @extend xxx;
            }
        }
    }
}
```

this lead to:

> OUT OF BOUNDS: '.new' append outside of '%xxx' (2 vs 1).)

It is not too important, it was just a use-case without an actual need behind it. But would it be possible to make that work? Or is it because of SASS, interpreting all @includes  before @extend?

PS.: do you know how to add an @ without mentioning someone?
